name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: cmake_config
      run: cmake -Bbuild .
    - name: build
      run: cmake --build build
    - name: test
      run: cd build && ctest
